---
- name: Install base deps
  apt:
    name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release, git]
    state: present
    update_cache: true

- name: Add Docker GPG key
  shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    chmod a+r /etc/apt/keyrings/docker.asc
  args: { creates: /etc/apt/keyrings/docker.asc }

- name: Add Docker apt repo
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

- name: Install Docker Engine & compose plugin
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Ensure docker is running
  service:
    name: docker
    state: started
    enabled: true