---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Deploy vhost (LB → containers)
  template:
    src: assugan.conf.j2
    dest: /etc/nginx/sites-available/assugan.conf
    mode: "0644"
  notify: reload nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/assugan.conf
    dest: /etc/nginx/sites-enabled/assugan.conf
    state: link
    force: true
  notify: reload nginx

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Test nginx config
  command: nginx -t
  changed_when: false

- name: Reload nginx
  service:
    name: nginx
    state: reloaded

